#!/usr/bin/env python3
"""Render the published statistics from a stats JSON snapshot.

This is a *renderer*, not a second statistics implementation. The numbers are
computed once in the Gerrit tree (`bazel run //tools/openapi:stats -- --json`) and
handed here; this script only accumulates them into a per-release history and
formats STATISTICS.md. That keeps a single source of truth for the figures -- there
is exactly one place that counts endpoints/schemas/fields, and it lives next to the
spec it counts.

Flow (driven by ./update.sh):
  bazel run //tools/openapi:stats -- --json  >  snapshot.json
  tools/gen_stats.py --stats snapshot.json --date YYYY-MM-DD

It upserts the snapshot into stats/history.json keyed by info.version (a release
supersedes its own -SNAPSHOT row) and re-renders STATISTICS.md: the current surface,
a per-area table, and a release-over-release history table.

Usage: tools/gen_stats.py --stats <snapshot.json> [--date YYYY-MM-DD]
"""

import argparse
import datetime
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HISTORY = os.path.join(ROOT, "stats", "history.json")
STATISTICS = os.path.join(ROOT, "STATISTICS.md")

# Method columns shown in the per-area table, in a stable order.
METHODS = ("GET", "POST", "PUT", "DELETE")


def version_key(version):
    """Sort key: (major, minor, patch, is-release). A -SNAPSHOT sorts *before* its
    release so the in-development row floats just under the tagged one."""
    base = version.split("-", 1)[0]
    parts = tuple(int(x) for x in re.findall(r"\d+", base))
    parts = (parts + (0, 0, 0))[:3]
    is_release = 0 if "-" in version else 1
    return (parts, is_release)


def upsert(releases, snapshot, date):
    """Replace any row with this version; a release also evicts its own -SNAPSHOT row.
    Returns the release list, newest first."""
    version = snapshot["version"]
    stale = {version}
    if "-" not in version:  # a tagged release supersedes the SNAPSHOT it came from
        stale.add(version + "-SNAPSHOT")
    kept = [e for e in releases if e["version"] not in stale]
    entry = dict(snapshot)
    entry["date"] = date
    kept.append(entry)
    kept.sort(key=lambda e: version_key(e["version"]), reverse=True)
    return kept


def pct(part, whole):
    return "%d%%" % (100 * part // whole) if whole else "n/a"


def table(header, aligns, rows):
    """A GitHub-flavored Markdown table. `aligns` is per-column 'l' or 'r'."""
    sep = ["---:" if a == "r" else "---" for a in aligns]
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def render(history):
    releases = history["releases"]
    cur = releases[0]
    ep = cur["endpoints"]
    sc = cur["schemas"]
    doc = cur["documentation"]
    bm = ep["by_method"]

    methods = " · ".join(
        "%d %s" % (bm[m], m) for m in METHODS if bm.get(m)) or "—"
    out = []
    out.append("# Gerrit OpenAPI — statistics")
    out.append("")
    out.append(
        "_Generated by `tools/gen_stats.py` from the published specs on every "
        "`./update.sh`; do not edit by hand. The figures are computed in the Gerrit "
        "tree (`//tools/openapi:stats`) and only formatted here._")
    out.append("")
    out.append("## Current — Gerrit %s (%s)" % (cur["version"], cur["date"]))
    out.append("")
    out.append("- **Endpoints:** %d operations across %d paths — %s"
               % (ep["operations"], ep["paths"], methods))
    out.append("- **Request shape:** %d with a request body · %d with query/path params"
               % (ep["with_request_body"], ep["with_params"]))
    out.append("- **Schemas:** %d component schemas (%d enums), %d properties"
               % (sc["count"], sc["enums"], sc["fields"]))
    out.append("- **Domains (tags):** %d" % ep["domains"])
    out.append("- **Documentation coverage:** %s%%" % doc["coverage_pct"])
    out.append("")
    out.append("### By area")
    out.append("")
    area_rows = []
    for name, c in cur["by_area"].items():
        area_rows.append([name, c["ops"], c.get("GET", 0), c.get("POST", 0),
                          c.get("PUT", 0), c.get("DELETE", 0),
                          pct(c.get("documented", 0), c["ops"])])
    out.append(table(
        ["Area", "Ops", "GET", "POST", "PUT", "DELETE", "Docs"],
        ["l", "r", "r", "r", "r", "r", "r"], area_rows))
    out.append("")
    out.append("## Release history")
    out.append("")
    out.append(
        "One row per published `info.version`; the `-SNAPSHOT` row tracks the "
        "in-development release and is replaced when it is tagged.")
    out.append("")
    hist_rows = []
    for e in releases:
        hist_rows.append([e["version"], e["date"], e["endpoints"]["operations"],
                          e["schemas"]["count"], e["schemas"]["fields"],
                          "%s%%" % e["documentation"]["coverage_pct"]])
    out.append(table(
        ["Version", "Date", "Endpoints", "Schemas", "Fields", "Doc coverage"],
        ["l", "l", "r", "r", "r", "r"], hist_rows))
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stats", required=True,
                    help="stats snapshot JSON from //tools/openapi:stats --json")
    ap.add_argument("--date", default=datetime.date.today().isoformat(),
                    help="ISO date to stamp this snapshot (default: today)")
    args = ap.parse_args()

    snapshot = json.load(open(args.stats))
    if os.path.exists(HISTORY):
        history = json.load(open(HISTORY))
    else:
        history = {"schema": 1, "releases": []}
    history["releases"] = upsert(history["releases"], snapshot, args.date)

    os.makedirs(os.path.dirname(HISTORY), exist_ok=True)
    with open(HISTORY, "w") as f:
        json.dump(history, f, indent=2)
        f.write("\n")
    with open(STATISTICS, "w") as f:
        f.write(render(history))

    print("stats: %s @ %s -> %d release(s) in history"
          % (snapshot["version"], args.date, len(history["releases"])))


if __name__ == "__main__":
    main()
